# Generated by Django 5.0.7 on 2024-07-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_id', models.IntegerField(unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('cart_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('abandoned_checkout_url', models.URLField(blank=True, null=True)),
                ('is_abandoned', models.BooleanField(default=True)),
                ('recovery_messages', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EcommercePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_intervals', models.CharField(max_length=255)),
            ],
        ),
    ]
