# Generated by Django 5.0.7 on 2024-07-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbandonmentCheck', '0002_checkoutstatus_ecommerce_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_interval', models.CharField(max_length=255)),
                ('eta', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('user_id', models.IntegerField()),
                ('message', models.TextField()),
                ('checkout_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AbandonmentCheck.checkoutstatus')),
                ('ecommerce_platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AbandonmentCheck.ecommerceplatform')),
            ],
        ),
    ]
